### ISSUE TITLE
Highly suggest using sass 

### ISSUE THREAD

**Issue by MichaelHillcox** [SpongePowered/SpongeHome#10]
Title says it all. Its much better for pages like this. Variables and other very useful tools.

**Comment by jamierocks** [comment]
If a preprocessor is to be used there should probably be some sort of discussion as to which one it should be: scss vs sass vs less etc.

**Comment by MichaelHillcox** [comment]
Sass is the nicest to work with but not the most powerful if you want raw power then we should look at less. Other wise you are looking at scss but it's a little less nice to work with. Sass is that nice cosy middle ground.

**Comment by jamierocks** [comment]
I actually tend to use scss, but don't have all too much reason for using except bourbon/neat/bitters uses it :P

**Comment by MichaelHillcox** [comment]
I would suggest looking into sass a little more. I know some people hate the 'there is no syntax' thing but at the same time they have strict rules for formating that are easy to follow and the code ( in my opinion ) looks very tidy. I am a neat freak so that is very important.

**Comment by jamierocks** [comment]
Yeah it does look neat - probably something I should take a look in in greater detail.

**Comment by MichaelHillcox** [comment]
@jamierocks I've actually added it into my pull request #9 Have a look if you would like.

**Comment by Zidane** [comment]
Closing this as it already happened in @MichaelHillcox 's PR.
