### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeHome#103]
Because there is no 'OCD minor issues' issue I have to create this one. Also I didn't want to create a PR just for this.

[In this line](https://github.com/SpongePowered/SpongeHome/blob/0d271ee2d4dedac62fb11d4bb4f107536b4e9a1d/templates/base.html#L100) should be a space between 'on' and 'GitHub'.

**Comment by Tzky** [comment]
Closing in favor of #104.
Thanks for reporting it :)
