### ISSUE TITLE
Website does not properly redirect to HTTPS

### ISSUE THREAD

**Issue by stephan-gh** [SpongePowered/SpongeHome#110]
http://www.spongepowered.org redirects all HTTP requests to HTTPS, however that doesn't seem to happen for http://spongepowered.org and http://www-staging.spongepowered.org.

This cannot be reproduced on Chromium based browsers because they redirect it internally (without contacting the server) because `spongepowered.org` is on the preloaded HSTS list (including all subdomains).

~~I've noticed the problem because the HTTP version seems to have all `<script>` tags stripped, so the announcements won't show when browsing the page on HTTP.~~

The best solution would be to extend the HTTP -> HTTPS redirects to the other subdomains so visitors on all addresses get redirected to HTTPS.

**Comment by lukegb** [comment]
The HTTP version doesn't have all the `<script>` tags stripped, so I don't know why you're seeing that in particular. (At least, not for curl or Firefox...)

**Comment by stephan-gh** [comment]
@lukegb ~~I don't know why the `<script>` tags were stripped for me, but~~ we really should just redirect all HTTP requests to HTTPS.

**Comment by progwml6** [comment]
@Minecrell what browser/os was this under?

**Comment by stephan-gh** [comment]
@progwml6 I don't get redirected on Firefox (Chrome redirects internally because `spongepowered.org` is on the preload HSTS list).

**Comment by JBYoshi** [comment]
`http://spongepowered.org` redirects to HTTPS now... but not `https://spongepowered.org`. It goes to `https://production-spongehome.apps.spongepowered.org/`. Weird.

`http://www-staging.spongepowered.org` is unaffected.

**Comment by progwml6** [comment]
the issue above is happening in firefox, there's nothing in the rules to explain why this is occurring

**Comment by JBYoshi** [comment]
A raw `GET` to the server returns a "301 Moved Permanently" with a `Location` header of `https://production-spongehome.apps.spongepowered.org/`.

![Screenshot](https://cloud.githubusercontent.com/assets/12983479/20459712/e82fca32-ae90-11e6-8885-4da0c7af88c9.png)

**Comment by stephan-gh** [comment]
Doesn't happen anymore for me, redirection works fine now.
