### ISSUE TITLE
If nobody else has seen

### ISSUE THREAD

**Issue by MichaelHillcox** [SpongePowered/SpongeHome#115]
https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/

Looks like the download buttons aren't working on the current live website.

**Comment by stephan-gh** [comment]
The link is correct, the downloads page is just down. @lukegb

**Comment by MichaelHillcox** [comment]
Thought as much :)

**Comment by MichaelHillcox** [comment]
Fixed
