### ISSUE TITLE
Forums / Plugins completely offline, says server is offline

### ISSUE THREAD

**Issue by aylacullen** [SpongePowered/SpongeHome#117]
Says:

```
503 Service Unavailable

No server is available to handle this request.
```

**Comment by JBYoshi** [comment]
Still down. Possible reasons:
- The forums may be doing an [upgrade](https://github.com/discourse/discourse/commits/master).
- There have been [plans](https://github.com/SpongePowered/Ore/issues/170) to migrate the login system to a [separate website](https://github.com/SpongePowered/SpongeAuth), and the forums may be purposefully down so no changes occur during the migration to mess it up.

**Comment by aylacullen** [comment]
Update: it's back online now.  Closing as resolved.

**Comment by progwml6** [comment]
for reference @JBYoshi we run multiple instances so that upgrades don't result in taking the forums down
