### ISSUE TITLE
Update for changes in Montserrat font

### ISSUE THREAD

**Issue by stephan-gh** [SpongePowered/SpongeHome#124]
Montserrat was recently updated on Google Fonts and the new version looks a bit different. The bold version is now much bolder. A new semi-bold version was added which looks similar to the previous version.

The SPONGE button looks a bit squashed now. We have a reduced `letter-spacing` currently, however it looks quite weird with the new font version:

  | Old | Now |
  | - | - |
  | ![](https://i.imgur.com/bRglNLs.png) | ![](https://i.imgur.com/2zmEk7Q.png) |

  New version with `letter-spacing` removed:

  ![](https://i.imgur.com/UJQpkMk.png)

---
We need to look through the pages and check whether usage of Montserrat SemiBold would be more appropriate for some headings. For reference, I've uploaded a version with the old font here: https://spongy.github.io/SpongeHome-PRs/123/

The new font version is already live at https://www.spongepowered.org

**Comment by Tzky** [comment]
~I'd keep the current look. If that means that we have to use Montserrat semibold (is this option available?), so be it.~

EDIT:
Just doublechecked. I'd keep everything with the new font. The only change i'd make is the spacing on the dropdown (shown above). Everything else is fine.

**Comment by stephan-gh** [comment]
Fixed in https://github.com/SpongePowered/SpongeHome/pull/125
