### ISSUE TITLE
Use icon font for social icons instead of images

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeHome#13]
Replace social link images with FA

**Comment by MichaelHillcox** [comment]
@Tzky in my last push #9 I moved us away from FontAwesome. Not that I have anything against it. Just that it was not constant with the forums and docs etc. We are not on Fontello which matches the forums. To rectify this I have changed the colour of the original ones to make them all look a little nicer. https://github.com/MichaelHillcox/SpongeHome/commit/fb28ee8a19e8e78d51a659cc9a1b3ed4b89c3ae0

**Comment by Tzky** [comment]
Oh, it doesn't need to be FA, any icon font is fine. I'd just like to get the images replaced.

**Comment by MichaelHillcox** [comment]
@Tzky I can find the reddit icon on any font. Even FA don't have it. and then nothing seems to have twitch other than FA the images are fine at the moment or do you not like them?

**Comment by Tzky** [comment]
According to fontello.com FA 4.3.0 has reddit and twitch.

I'd prefer an icon font instead of images because a) it improves loading times b) it keeps the size of the page down c) we use icon fonts anyways

**Comment by MichaelHillcox** [comment]
Okay, I'll merge FA back into the site and swap over the icons.

**Comment by MichaelHillcox** [comment]
That should fix it. Its in my #17

**Comment by Tzky** [comment]
Resolved in b97d0c1b585f5fd1d014ed860f5f232b5afd3ad1 , we're using FontAwesome for now.
