### ISSUE TITLE
Downloads page version selector usability issue

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeHome#131]
When I go to the downloads page on my phone, there is only one Minecraft version visible without using the dropdown menu. When I select something in that dropdown menu, the latest version is the only one visible, and it looks (from the version selector alone, though usually someone would be focusing on that) as if the selected version hadn't changed. For example, in this screenshot I have selected Minecraft 1.10.2 (iPhone 5s, iOS 10.3.2):

![img_2624](https://user-images.githubusercontent.com/12983479/26976419-5a860884-4ce9-11e7-97e6-8e98da274154.PNG)

**Comment by ryantheleach** [comment]
I ran into this problem and I think it's a large reason why the download page has mildly confused me.

![image](https://user-images.githubusercontent.com/141554/34971931-fb4ec53e-facd-11e7-9492-3fa5621df627.png)

Showing 1.12, but downloads listed are 1.10

**Comment by stephan-gh** [comment]
Originally I wanted to make the dropdown arrow colored, but I couldn't quite get that working without ugly hacks. It might make more sense to always make sure the currently selected version is shown on top-level, i.e. add them to the main list when they are selected.

**Comment by MichaelHillcox** [comment]
Who is downloading the .jar on their phone? Not to be that guy but like, it seems like a real non issue to me? I work in the sector and this is the sort of thing you have to fingure out if you want to waste time on or not for the 0.1%

**Comment by stephan-gh** [comment]
The same applies on the desktop.

**Comment by MichaelHillcox** [comment]
@Minecrell Ignore me then, I miss understood the issue 😨

**Comment by stephan-gh** [comment]
Moved to https://github.com/SpongePowered/SpongeDownloads/issues/2
