### ISSUE TITLE
forums.spongepowered.org Poll Data Load Issue

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/SpongeHome#133]
Hello, I conducted a poll [here](https://forums.spongepowered.org/t/quick-poll-server-with-mods-vs-server-without-mods/18663), and now I need to retrieve the name of users who voted to participate in the alpha testing of a plugin I've developed. When I tried to click on: "Show Results" > "↓ ", a infinite loading symbol keeps rolling and doesn't show me any results. Below are my specs.

**OS:** Windows 10
**Browsers:** Google Chrome, Mozilla FireFox

I originally posted my issue [here](https://forums.spongepowered.org/t/polls-bug/18672), on May 1st, but it seems like it wasn't acknowledged, so I posted it [here](https://github.com/SpongePowered/SpongeCommon/issues/1405) yesterday, June 21st, as I figured an administrator would see the issue, which one of them did, but instead of addressing the issue, the administrator closed the issue and said the polls worked fine. The polls work fine for simple things like voting, but when trying to retrieve data e.g. who voted, it does not work, otherwise I would have no need for these bug reports, and now I've arrived here.

**Comment by jamierocks** [comment]
This is the repository for SpongeHome - the SpongePowered website, not the forum.

**Comment by SjsolisZXA** [comment]
The bug is in the forums site itself, which is part of the website.

**Comment by jamierocks** [comment]
The forum is a completely separate web property from the SpongePowered website. This issue tracker is for issues pertaining to the SpongePowered site.

**EDIT**: You were previously directed to report this on the forum -> https://github.com/SpongePowered/SpongeCommon/issues/1405#issuecomment-310343713
