### ISSUE TITLE
[Sponsors] Re-work page to flow a bit better and be more inviting to potential sponsors

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#14]
We've got the content but its just a massive wall of text + a few background changes. Its not inviting to potential sponsors and frankly does a poor job of making someone WANT to sponsor Sponge (beyond the obvious).

Bringing in @mcsnetworks to this as he should be involved with how the page flows, reads, and looks.

Pretty much, I see the following as needed:
- [ ] Revise backgrounds entirely
- [ ] Revise wording entirely. Keep things short and to the point (Who we are, what we offer, what we need, where are we heading)

**Comment by Zidane** [comment]
I welcome thoughts and ideas...especially if peeps have any mockups or such.

**Comment by MichaelHillcox** [comment]
@Zidane I can work on this today. I can make the page look a lot tidier and to the point. I will move away from the background idea. For the homepage that is great but not for a sponsors. I will push it to #17

**Comment by MichaelHillcox** [comment]
@Zidane I should have greatly improved it for you guys

**Comment by Tzky** [comment]
I pulled @MichaelHillcox changes to the sponsors page in. Does it resolve this issue?
e35426bbdf1e992dd782f6818cb9293257cac4ac

**Comment by Tzky** [comment]
Bump. Is this still an issue, @Zidane? The whole page got more or less changed since you reported this issue... :)

**Comment by MichaelHillcox** [comment]
@Tzky I would definitely say that this issue has been fixed.
