### ISSUE TITLE
Rework downloads page

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeHome#140]
Adding to https://github.com/SpongePowered/SpongeDownloads/issues/8

Downloads page should be removing the highlight on Latest Build and instead show Recommended Build at the top, hiding all other versions in a spoiler like the [Forge site](http://files.minecraftforge.net/) does.

Stable should be renamed to Release, as it doesn't imply stability. Recommended Build will be instead the stable version.

Something like this:
![](https://i.imgur.com/2Yc5AbS.png)

(moved from https://github.com/SpongePowered/SpongeDownloads/issues/9)

**Comment by stephan-gh** [comment]
Moved to https://github.com/SpongePowered/SpongeDownloads/issues/1
