### ISSUE TITLE
Add opt-in/opt-out for Google Analytics

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/SpongeHome#147]
Something that was discussed last night at SPAM was the use of Google Analytics and its role with the GDPR. @Zidane asked me to post this here so it doesn’t get lost.

I don’t know GA that well, so I did a quick bit of research Google Analytics about who is what with regards to the data- Google is the **Data Processor**, we are the **Data Controller** - _we_ control what data is sent to Google making us responsible.

We need to ensure the following:

* IP Anonymisation is on - as IP addresses are considered personal data under the GDPR in cases as these.
* That GA is opt in - unfortunately as a GA client ID is generated per user, this is considered **psuedomysation**, not **anonymisation**, as it could be de-anonymised if linked with other data such as IP addresses.
* That no data that could be seen as personal is even _sent_ to Google, even though I am aware that GA has filters that can be used to strip such data, it’s too late at this point because the data has been sent.

The biggest thing for us is the opt-in capability. A box on first page visit is fine with a blurb about accepting cookies for essential and analytic purposes, with an option to “decline” or “review”. A page is also needed to ensure that this can be turned on or off at any time.

**We may need to do this with Ore and the Forums too**. I’m not familar with which technologies are being used where, but we should be consistent wherever we are.

**Comment by stephan-gh** [comment]
Frankly I'm wondering if we need GA at all. I never look at it and I haven't heard of anyone else using it regularly (yet?). Data is best saved by not collecting it at all.

If we do want some basic statistics it might make more sense to set up a self-hosted version of [Matomo/PIWIK](https://matomo.org). It's open-source, and probably has much more privacy features than GA. As far as I know it could even run entirely without cookies (with less accuracy). With the GDPR it's always much easier if data is never sent to some other third party.

I haven't checked for GA, but at least Matomo can be also configured to only track with opt-in: https://developer.matomo.org/guides/tracking-javascript-guide#asking-for-consent

**Comment by dualspiral** [comment]
We've just talked about this at SPAM, and we think it's better to simply remove GA.
