### ISSUE TITLE
Sponge logo and arrow is too close

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeHome#153]
![bildschirmfoto vom 2018-12-05 22 03 21](https://user-images.githubusercontent.com/10366256/49544010-05e12400-f8da-11e8-8e02-4fae5a9d0042.png)

Spongie needs a bit more freedom I think, the arrow is so close.

`Chrome Version 70.0.3538.110 on Linux Mint`

Edit: This only happens when viewing a topic, not when being in the Discourse overview.

**Comment by ItsDoot** [comment]
Reproduced on Chrome 70.0.3538.110, Windows 10

**Comment by felixoi** [comment]
Moved to https://github.com/lukegb/discourse-spongepowered-navbar/issues/8

**Comment by jamierocks** [comment]
I can also confirm on Firefox 63.0.1, however this is an issue for https://github.com/lukegb/discourse-spongepowered-navbar/ :)
