### ISSUE TITLE
Add Discord to social buttons at bottom of page

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeHome#156]
as title, put it next to reddit/twitch etc

**Comment by jamierocks** [comment]
Ideally this would involve replacing an existing social link - Facebook seems the best to replace imo, though Reddit could work too.

**Comment by jamierocks** [comment]
As an aside, this has always been something to do - just font awesome didn't have a Discord icon back in 2016.

Good opportunity to go through Home and update font-awesome, and look into whether we can use one of their smaller distributions.
