### ISSUE TITLE
classie.js errors

### ISSUE THREAD

**Issue by octylFractal** [SpongePowered/SpongeHome#24]
Doesn't seem to happen every time, but occasionally this pops up in the JS console: `classie.js:33 Uncaught TypeError: Cannot read property 'classList' of null`.

**Comment by progwml6** [comment]
its been consistently in my js console on chrome on my macbook
classy is being used by this file
 https://github.com/SpongePowered/SpongeHome/blob/master/assets/js/cbpAnimatedHeader.js
