### ISSUE TITLE
Add license to repo and pages

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeHome#25]
We need to choose a license for the landing page.

**Comment by progwml6** [comment]
this should probably be MIT to be consistent with our other projects unless we want to be more selective with the licensing for our branding

**Comment by Zidane** [comment]
I agree on MIT but the assets need to be some other license.

Thoughts?

@SpongePowered/contributors 
@SpongePowered/developers

**Comment by liach** [comment]
creative commons?

**Comment by Tzky** [comment]
The assets still need their own repo, i'd choose a Creative commons license there. The page itself should become mit, like the whole project.

**Comment by Tzky** [comment]
Opened #83 to resolve this issue, please comment there.

**Comment by Tzky** [comment]
I just merged #83, so closing this issue.

The license excludes the assets currently, we still need to choose a license for them elsewhere.
