### ISSUE TITLE
Dynamic width text is a little overreactive

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeHome#26]
Compare the following:
![smaller](http://puu.sh/oeaGK/98970b12e2.png)
![larger](http://puu.sh/oeaHI/8059aaed9c.png)

The first image is the website in a smaller width sized window, while expanding the window just past that width will cause the text to crop up on the side and still only take 25% of the space.

**Comment by Tzky** [comment]
This should be fixed with 901de56
