### ISSUE TITLE
Replace landing background

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeHome#31]
The landing background while good is not using the same yellow as SpongePowered officially uses. We have a brand to maintain, let's keep it consistent.

**Comment by progwml6** [comment]
@gabizou is any particular site considered the authoritive one in regards to coloring & the CSS?

**Comment by windy1** [comment]
I kind of like [this](http://imgur.com/GGYlXvf) :p ([background](http://imgur.com/dBY7pj4))

**Comment by Tzky** [comment]
@progwml6 
Afaik the "official" Sponge yellow is #f6cf17

I'd take the topbar from the forums as the main one and change all the others. The first step i made towards the unified sites was porting the topbar from the forums to the docs. However the forums topbar is still Entypo based, we need to change that (@lukegb, maybe?)

**Comment by progwml6** [comment]
fixed in https://github.com/SpongePowered/SpongeHome/commit/b71029615b711990eb126994c1e265e25b72bc07
