### ISSUE TITLE
Better wording

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeHome#32]
"Our Team has decades of collective experience of working on Minecraft."
This sounds like complete bull with regards to how many people actually work on the project and the collective experience. If anything, this shouldn't make the same sort of language claim that manufacturers make with hard drives where they last "over a hundred thousand hours." which is a farce at best.

**Comment by progwml6** [comment]
I think mentioning diverse backgrounds from different parts of the MC & gaming communities might be a better fit for this location.

**Comment by mbax** [comment]
"Hours of collective experience playing Minecraft."

**Comment by Inscrutable** [comment]
How about "Our Team is drawn from diverse parts of the Minecraft modding community, and has broad and extensive experience working with Minecraft and modding."   ... or edit for brevity.

**Comment by Tzky** [comment]
Isn't this resolved anyways? The whole About section got changed...

**Comment by gabizou** [comment]
@Tzky it's still an issue because instead of it being in the About section, it's now at the bottom under "Experienced Staff".

**Comment by jamierocks** [comment]
How is @Inscrutable's suggestion @gabizou ?

**Comment by gabizou** [comment]
@jamierocks that's fine.

**Comment by jamierocks** [comment]
Alright - making a pr now ;)
