### ISSUE TITLE
Move Social Media buttons as smaller icons

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeHome#33]
Social media buttons don't need to take so much space of the website, in fact they could just sit right below the main Sponge logo (or simply on the side of the website).

**Comment by Tzky** [comment]
I made them smaller for now. I'm not sure where we should relocate them. I made a quick test with them just below the main logo and it didn't look nice. If you still feel they should get relocated let me know.

**Comment by Tzky** [comment]
Closing for now, as there weren't any further complains about the (now smaller) social buttons
