### ISSUE TITLE
Needs a Dockerfile

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/SpongeHome#37]
Someone (maybe me) needs to create a Dockerfile for this.

**Comment by progwml6** [comment]
a www-staging site or something similar would be useful as well until this site is ready for production

**Comment by Tzky** [comment]
@jamierocks has alteady setup a staging site:

http://www-sponge-staging.jamierocks.uk/

**Comment by progwml6** [comment]
its a good start however @Tzky it is not being auto built

**Comment by progwml6** [comment]
@lukegb jenkins jobs have been added for this repo as well
