### ISSUE TITLE
Polish icons

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#4]
@Tzky @Owexz 

Thinking you two were going to work on this.

**Comment by MichaelHillcox** [comment]
What icons? I may have already fixed this in #9

**Comment by Tzky** [comment]
Bump. Which icons? Is this resolved?

**Comment by MichaelHillcox** [comment]
Going to have to say this one is done seeing as we are not getting an answer and since the time this was first made the majority of the icons have been changed.

**Comment by jamierocks** [comment]
Fairly certain this can be closed ;)
