### ISSUE TITLE
Remove Entypo

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeHome#40]
We're using FontAwesome now, so Entypo isn't needed anymore.

**Comment by jamierocks** [comment]
I did that XD

**Comment by progwml6** [comment]
entypo was removed when we moved the assets to use cdnjs in commit https://github.com/SpongePowered/SpongeHome/commit/e4c8c6f077ef15fe804aeff37f2d4d72f454de01

**Comment by Tzky** [comment]
Oh well. I must've overlooked that. Nvm then.
