### ISSUE TITLE
Improve contrast between text and background.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeHome#49]
![image](https://cloud.githubusercontent.com/assets/141554/14766787/895f2488-0a55-11e6-86b9-b9cb7679fa12.png)

![image](https://cloud.githubusercontent.com/assets/141554/14766790/9fb07e12-0a55-11e6-88e4-0f8b20254e0b.png)

**Comment by Tzky** [comment]
Yes, we're aware of this issue. Especially the Enjin logo is almost unreadable.

**Comment by Tzky** [comment]
The sponsors sevtion got overhauled, so this issue is solved. The about section however is still the same. I must admit that i don't find it hard to read... 

@ryantheleach:  Is this still an issue?

**Comment by MichaelHillcox** [comment]
@Tzky This is also very much no longer an issue.
