### ISSUE TITLE
Sponsor/Support Us flow is currently quite poor

### ISSUE THREAD

**Issue by Mumfrey** [SpongePowered/SpongeHome#53]
Split off from #52 because typing it out I realised it doesn't really count as a "minor issue":
- [x] The _Sponsor / support us_ flow is confusing as hell:
  
  The home page has an _Interested in Sponsoring Sponge_ button which links to `/sponsors`, which makes sense. However it then has a button cryptically labelled _Support Us_ with a random box next to it under the **About** heading which links to Patreon (???) though patreon and/or supporting the project isn't mentioned in the preceding text under the **About** heading
  
  The _Sponsor us_ button at the bottom of `/sponsors` is a `mailto:` link, which is again not very obvious.

I think the _Interested in Sponsoring Sponge?_ CTA button doesn't need any alteration and works very well. However, I suggest that the sponsor/support us flow be re-evaluated to make the distinct CTAs clearer. Examples of things which could be done to achieve this:
- More obvious CTA buttons in place of the cryptic _Support Us_ button, eg. provide multiple buttons:
  - _Support us on Patreon_ or maybe _Become a Patron_
  - _Become a Sponsor_ -> also link to `/sponsors`
  - _Get Involved_ -> link to new page with "ways to help" listing github, docs, forums, etc.

Add "get involved" page with other ways that people can contribute, some example content:

> - **GitHub**
>   _Are you a Java programmer? Want to contribute to the most ground-breaking project the Minecraft community has ever seen, or just love testing stuff to destruction and then writing long and detailed bug reports about it? Come get involved on GitHub!_
>   
>   _Want to know how? Check out our **getting started documentation**!_
> - **SpongeDocs Project**
>   _Coding isn't your thing but you love helping others, get a thrill from hammering out the perfect prose, or just love nit-picking other peoples' grammar? Our fearsome and frankly unstoppable documentation team, led by the reknowned international Man of Mystery **Inscrutable** himself (hyperbole? what's that?) will be delighted to induct you into their team of infamous brigands, cunning wordsmiths and formidable grammar nazis._
> - **Sponge Fora**
>   _Looking for something more casual? Somewhere you can hang out with fellow Spongeoneers? Critique new plugin ideas and help people out with Sponge? Look no further than the **Sponge Forum**. Powered by Discourse to ensure just the right balance between awesome ease of use and terrifying addictiveness._

Follow at the bottom with another patronise CTA for people maybe landing on the get involved page directly who haven't navigated via the home page:

> - **Not enough**
>   _Want to give us more than your time? You can also give us your money! We promise not to just buy jaffa cakes with it. **Click here to give us all of your money**_

Okay, tongue in cheek but you get the idea.

**Comment by Zidane** [comment]
I love these descriptions above and I second your criticisms.

**Comment by Mumfrey** [comment]
Frankly they can bin all of the text as long as we keep the term _Spongeoneer_ in there as far as I'm concerned :smile:

**Comment by Tzky** [comment]
Most (if not all) of this should be resolved in 9400895, so closing for now.
Please reopen if you feel that an issue wasn't fully adressed.
