### ISSUE TITLE
Clarify setup and run instructions for Go noobs.

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeHome#55]
I'm currently trying to properly setup Go and SpongeHome plus run it and it doesn't work out well when following the instructions provided in the readme.

**Comment by jamierocks** [comment]
What part are you struggling with?

**Comment by Tzky** [comment]
I've set it up now, but the instructions could get some love especially regarding `$gopath`

**Comment by humaidq** [comment]
@Tzky Me too! But I figured it out after ~~some~~ lots of research.

**Comment by Tzky** [comment]
Just to document which issues i was running into:
- `go get URL` wasn't working at first
- had to understand the folder structure of Go (which i wasn't forced to use later, but you never know...)
- had to add `$gopath` variable on win8.1x64

I somehow managed to get it into a working state though.

**Comment by jamierocks** [comment]
The instructions seem clear enough for me - seems as if a different tutorial for installing Go would help.
