### ISSUE TITLE
Update the link to the live server

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeHome#56]
The current link (https://rawgit.com/SpongePowered/SpongeHome/master/index.html) no longer works due to the Go setup.
![spongehome-url](https://cloud.githubusercontent.com/assets/12983479/14869301/238b6d66-0c98-11e6-8f36-7f169ed827e1.png)

**Comment by jamierocks** [comment]
There is currently no official live server, however I have been running https://www-sponge-staging.jamierocks.uk/#page-top for my pull requests.

**Comment by Tzky** [comment]
@Owexz can you remove the link? I have insufficient rights.

**Comment by gabizou** [comment]
> @Owexz can you remove the link? I have insufficient rights.

Done :)
