### ISSUE TITLE
[Sponsors] Text formatting inconsistent in numerous areas

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#6]
Need to look into cleaning up the formatting on the sponsors page to be more consistent and more visually appealing.

**Comment by Aaron1011** [comment]
IMHO, one of the main issues is the contrast between the text and the sliding/moving background images. While they look amazing, it's often very difficult to read the text (particularly the string "SPONSORS", and the entire "Announcements" section).

**Comment by Zidane** [comment]
Closing this in favor of https://github.com/SpongePowered/SpongeHome/issues/14

**Comment by Zidane** [comment]
BUT Michael did fix much of the original concerns.
