### ISSUE TITLE
Style details

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeHome#61]
Looking over the home page at https://www-sponge-staging.jamierocks.uk/#page-top I just have a few thoughts. (continuing from IRC)
- [x] The main [Spongie logo has incorrect proportions](https://cloud.githubusercontent.com/assets/755713/14937032/094baf32-0ec9-11e6-8cb8-4badd756948d.png) for my display at 1080p.
- [ ] Having Spongie across "Get Sponge" section 3 times seems odd to me. We should probably remove the logo altogether there.
- [x] The colored text under the "Get Sponge" links don't really fit in. Maybe make them gray or something.
- [x] "Get Sponge" download links could use some background-color transitions. `ease 0.5s` looks good to me.
- [x] "Get Sponge" download links border width 2px -> 1px
- [x] The swamp image looks dreary and unappealing, should be replaced.
- [x] Sponsors are listed twice
- [x] All text on the image panels should be white
- [x] About text should be wider
- [x] Copyright text is too large, `font-size: 12px;` would be better plus `text-align: left;`

Otherwise really looking good guys, keep up the good work!

**Comment by jamierocks** [comment]
The first one seems to be an issue with Firefox's implementation of flexbox.

**Comment by Tzky** [comment]
I fixed the border width and the missing transitions of the buttons in 9e17737.
The about text is now wider too (901de56).

**Comment by Tzky** [comment]
0ab938e fixes the copyright notice at the bottom (it's `0.8em` and `text-align:left` now)

@windy1 
Is having Spongie 3 times in the downloads section still an issue?

**Comment by windy1** [comment]
No I think it's OK actually.
