### ISSUE TITLE
Change color of 'Vanilla' in SpongeVanilla logo

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeHome#70]
The word 'Vanilla' on the Get Sponge section's 'SpongeVanilla' part is a light-tan color. Unfortunately, it's almost unreadable due to the low contrast between it and the background.

**Comment by jamierocks** [comment]
I'm no expert at design but perhaps a green or blue would be nice?

**Comment by Tzky** [comment]
Tbh i'd like to have a consistent color across all three logos plus remove the Spongie face.
So maybe switch the red, purple and light-yellow to a single brand color?

**Comment by humaidq** [comment]
I would prefer if these images were SVG and the colours could be easily swapped. I wish it was for all the images.

**Comment by jamierocks** [comment]
I think that the different colours give them some difference, keeping them separated - for that I think the separate colours should remain.

**Comment by Faithcaio** [comment]
Maybe just put a thin black border around it?

**Comment by windy1** [comment]
Perhaps something like this?

http://imgur.com/zGGt0Fn

**Comment by jamierocks** [comment]
@windy1 ooh - that's nice

**Comment by windy1** [comment]
@jamierocks 

http://imgur.com/a/PIcZd

**Comment by Tzky** [comment]
@windy1: Can you style them according to the soon to be branding manual?
Afaik there are some colour palettes in there.

Looks good, but we still need to get rid of the tripple Spongie face...

**Comment by windy1** [comment]
http://imgur.com/a/OQWeR

Here's an updated version. What is breaking the branding manual @Tzky besides the off brand colors here which I thought we were making an exception for.

**Comment by Tzky** [comment]
I was refering to the colors, that'd be the only thing you'd have to change. If we're making an exception here, then nvm.

**Comment by windy1** [comment]
Here's how it looks on the site.

http://imgur.com/SGbYgIc

**Comment by jamierocks** [comment]
i would make the vanilla colour slightly darker

**Comment by windy1** [comment]
This might be a better color although not really darker. Any darker and it just kind of looks brown so we should either stick with something like this or ditch the "cream" color entirely.

http://imgur.com/4zjf9Je

And here's an xcf of all of them if you wanna mess with them some more.

https://drive.google.com/file/d/0B3_zPvLGAA8MeC0xTVlnT1BqYVE/view?usp=sharing

**Comment by Tzky** [comment]
Hmm, what about using `#910020`, `#009172` and `#917300` ? 
(they're all on-brand colors)

**Comment by progwml6** [comment]
i think that @Tzky's colors  with @windy's images might look nice

**Comment by windy1** [comment]
Ask and thou shall [receive](http://imgur.com/a/PR2Qp) :pray:

**Comment by jamierocks** [comment]
:+1:

**Comment by Tzky** [comment]
Hmm, @windy1s logos look way better than the old. However i'd like to get rid of Spongie too. That's my try on it, i'm not happy with it yet, though. Left is my try, in the middle is windys, on the right is the old one. Thoughts?

![unbenannt](https://cloud.githubusercontent.com/assets/10940670/15039075/e0e72b4a-12a9-11e6-8194-3d5c5ef6b7f7.PNG)

**Comment by jamierocks** [comment]
I rather like @windy1's ones

**Comment by Tzky** [comment]
Agreed. That's why I already pushed them to master ;)

**Comment by Tzky** [comment]
Windys Logos with the onbrand colors solved this issue.
