### ISSUE TITLE
Purge Fastly cache?

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeHome#74]
Not exactly an issue, but a question:
Do we need to purge the fastly cache just like on the docs when building SpongeHome?

@lukegb will probably know... :)

**Comment by progwml6** [comment]
Yes we will, and I can look into this tonight assuming @lukegb doesn't get to it first

**Comment by Tzky** [comment]
It's been 19 days. 

Bump. ;)

**Comment by progwml6** [comment]
purging the fastly cache is simple(and working in local tests), however ensuring that it doesn't happen until the new version of the site has deployed is not, and requires some behind the scenes changes to get it running fully

**Comment by progwml6** [comment]
Update: code is mostly done, just working on how to identify if staging or production is running
