### ISSUE TITLE
Icons collide with each other on mobile device 

### ISSUE THREAD

**Issue by mattysweeps** [SpongePowered/SpongeHome#75]
Phone: Samsung Galaxy S6 Edge.

The forums/code/javadocs/etc icons run into each other.

Portrait:
http://postimg.org/image/6w7nejyqp/

Landscape:
http://postimg.org/image/i5l7i5ktd/

**Comment by Tzky** [comment]
I noticed this too, but couldn't find a quick fix yet.

**Comment by felixoi** [comment]
I also saw this. The columns are placed right but the content is bugging out.
http://imgur.com/E0dnRRU

**Comment by jamierocks** [comment]
Yeah - this is a simple fix. I'll get to it when schools finished.

**Comment by Tzky** [comment]
This should be resolved with 4680284
