### ISSUE TITLE
API Download link

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeHome#88]
IF the site is going to provide a link to download the API files as it is doing, then please, get the site fixed.
The page currently linked has up and died two months ago and is not dynamic, missing the 2+ months of files that exist since then.  
The dynamic page-updating part vomited on something from an auto-build in march and its preventing the page from displaying anything else

Otherwise, could a landing page be made for the destination target that will list the various API projects directly to the maven like https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/4.1.0-SNAPSHOT/  , rather, a landing page of all ^^ such links to project folders for each api project.

**Comment by Tzky** [comment]
Actually that's not an issue of SpongeHome, so closing this. However there seems to be an issue with the maven repo of the API and the website you mentioned, we're investigating it.Thanks for reporting :)
