### ISSUE TITLE
Change Sponge writing to actually fit branding guidelines

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#94]
In talking with our friends over at Resonant Rise, they brought up a good point that the writing at the top left on all navbars actually violates our own branding guidelines. This also does not help us in wanting to have a consistent image to people who visit our pages. We need to get the font changed to one that fits our guidelines (which is Montserrat I believe). This change will happen all across the board.

@Owexz @Mumfrey @windy1

**Comment by Mumfrey** [comment]
**Montserrat** is the identity font, which should be used for logo text and things like headings. For body fonts any sans font can be used (within reason, eg. use same font throughout entire publication/site) or use of **Lato** where possible is encouraged.

[Branding guidelines](https://drive.google.com/file/d/0B0_Vyme6I-EwTk9HUWtSdDNxaFU/view?usp=sharing)

**Comment by Zidane** [comment]
@Mumfrey 

I would argue that this isn't a body font and would argue further that it is most definitely a logo. Its the first to draw people's eyes on entering our sites and is a key part of our web identity.

**Comment by Mumfrey** [comment]
Do you mean the word **Sponge** on the navbar? Yes that's most definitely a logo and should therefore be **Montserrat**.

**Comment by Zidane** [comment]
@Mumfrey 

Correct (I'm lazy and didn't take a snip).

**Comment by Tzky** [comment]
Fixed in 6645d74.

**Comment by Mumfrey** [comment]
You used Montserrat Regular rather than Montserrat Bold.

**Comment by Tzky** [comment]
Yes, i'll correct that mistake in a bit and swap regular with bold. Thanks for mentioning this :)

Edit: Fixed in 7dcf7bb.
