### ISSUE TITLE
Add downloads link to 'Quicklinks Section'

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeHome#98]
Currently, 'Quicklinks Section' (containing the buttons 'Forums', 'Code', 'Javadocs', etc.) lacks a download button. The only way to download Sponge from the home page is to use the comparatively difficult-to-spot 'Downloads' button in the upper right-hand corner, or scroll a significant distance down to the 'Get Sponge' section.

Since people visiting the home page are probably going to be server owners (developers may have seen the Github page linked elsewhere), I think it makes sense to display a link to the 'Get Sponge' section much more prominently. This could be accomplished in one of two ways:
- Adding an additional button to the aforementioned 'Quicklinks Section'. This has the downside of adding yet another button to a section which already looks somewhat cluttered.
- Replacing the 'Javadocs' button. Since the javadocs are already linked from the SpongeAPI repository README, I don't think it's very useful to have a direct link on the home page- the people viewing the javadocs have probably already looked at the repository itself.

As a side note, it might be useful for someone with access to look at the Google Analytics stats for the number of clicks on those buttons (if no one has already).

**Comment by JBYoshi** [comment]
I'd say replace the Javadocs button. Most developers are using Maven/Gradle and an IDE, and since Maven and Gradle download the sources, the IDE gets access to the Javadocs via them.

**Comment by Tzky** [comment]
- The dropdown on the top left of the page already has a `Get Sponge` button. 
- I'll replace the link to the Javadocs on the grey main bar with a `Get Sponge` button.

Have a look at c2ba107.
